add backend API routes
SJSUCSClub/acm-website-server pull request #15
Opened 2024-10-09 02:03 UTC by kevintsoii

from #12

2024-10-11 00:55 UTC, knhn1004 requested changes

2024-10-11 00:55 UTC, knhn1004 commented on server/src/router/v1/events.ts
> +export default events;
add empty line

2024-10-11 00:55 UTC, knhn1004 commented on server/src/router/v1/equipment.ts
> +export default equipment;
add empty line

2024-10-11 00:55 UTC, knhn1004 commented on server/src/router/v1/company.ts
> +export default company;
add empty line

2024-10-11 00:55 UTC, knhn1004 commented on server/src/router/v1/projects.ts
> +export default projects;
empty line

2024-10-11 00:55 UTC, knhn1004 commented on server/src/router/v1/officers.ts
> +export default officers;
empty line

2024-10-11 00:55 UTC, knhn1004 commented on server/src/router/v1/majors.ts
> +export default majors;
empty line

2024-10-11 00:55 UTC, knhn1004 commented on server/src/router/v1/users.ts
> +export default usersRouter;
empty line

2024-10-11 00:57 UTC, ManasC478 submitted a review, later dismissed

2024-10-11 03:34 UTC, knhn1004 approved these changes

2024-10-14 23:20 UTC, knhn1004 requested changes
halt for now, we drastically changed the route structure

2024-10-18 01:25 UTC, closed without merging