feat: added majors data
SJSUCSClub/acm-website-server pull request #20
Opened 2024-10-11 02:43 UTC by ManasC478

2024-10-11 03:36 UTC, knhn1004 requested changes

2024-10-11 03:36 UTC, knhn1004 commented on db-scripts/createdb.sql
> +('Advertising, BS'),
we should probably put `Undeclared` at the beginning

2024-10-18 01:26 UTC, knhn1004 approved these changes

2024-10-18 01:27 UTC, knhn1004 approved these changes

2024-10-18 01:31 UTC, aaryauchamkeri approved these changes

2024-10-18 01:32 UTC, merged